version: "3.8"
services:
  
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      network1:

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - network1

  redis:
    container_name: redis
    image: redis:6.2-alpine
    networks:
      - network1
  
  app:
    container_name: fastapi_container
    build: ./src
    restart: always
    ports:
      - "8001:80"
    networks:
      - network1
    depends_on:
      - db

networks:
    network1:

volumes:
  tmpfs: